import assert from "node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";import vm from"node:vm";
function load(){const source=readFileSync(new URL("../utils/realtime-client.js",import.meta.url),"utf8");const module={exports:{}};vm.runInNewContext(source,{module,exports:module.exports,console,Date,Math,setTimeout,clearTimeout,encodeURIComponent});return module.exports;}
function fakeWx(){const sockets=[];return{sockets,connectSocket({url}){const handlers={};const sent=[];const socket={url,sent,onOpen(fn){handlers.open=fn},onMessage(fn){handlers.message=fn},onError(fn){handlers.error=fn},onClose(fn){handlers.close=fn},send({data}){sent.push(JSON.parse(data))},close(){handlers.close&&handlers.close()}};socket.handlers=handlers;socket.sent=sent;sockets.push(socket);return socket;}};}
test("realtime client queues commands, uses snapshot version, and recovers stale state",()=>{const{RealtimeClient}=load();const wx=fakeWx();const states=[];const errors=[];const client=new RealtimeClient({wxApi:wx,baseUrl:"ws://localhost:8080",userId:"u-1",onState:(state)=>states.push(state),onError:(error)=>errors.push(error)});client.sendCommand("room.create",{}, {roomId:null,expectedVersion:0});assert.equal(wx.sockets.length,1);wx.sockets[0].handlers.open();assert.equal(wx.sockets[0].sent[0].type,"room.create");wx.sockets[0].handlers.message({data:JSON.stringify({type:"room.snapshot",payload:{roomId:"r1",roomCode:"123456",version:7}})});client.sendCommand("room.ready",{ready:true});assert.equal(wx.sockets[0].sent.at(-1).expectedVersion,7);wx.sockets[0].handlers.message({data:JSON.stringify({type:"error",payload:{code:"STALE_VERSION"}})});assert.equal(errors.at(-1).code,"STALE_VERSION");assert.equal(wx.sockets[0].sent.at(-1).type,"game.reconnect");assert.ok(states.length>0);});


test("realtime client clears room snapshots after leaving",()=>{const{RealtimeClient}=load();const wx=fakeWx();const states=[];const client=new RealtimeClient({wxApi:wx,baseUrl:"ws://localhost:8080",userId:"u-leave",onState:(state)=>states.push(state)});client.connect();wx.sockets[0].handlers.open();wx.sockets[0].handlers.message({data:JSON.stringify({type:"room.snapshot",payload:{roomId:"r-leave",roomCode:"123456",version:2,phase:"WAITING"}})});wx.sockets[0].handlers.message({data:JSON.stringify({type:"room.snapshot.private",payload:{seat:0}})});wx.sockets[0].handlers.message({data:JSON.stringify({type:"room.left",payload:{closed:false}})});assert.equal(client.publicSnapshot,null);assert.equal(client.privateSnapshot,null);assert.equal(states.at(-1).roomLeft,true);client.sendCommand("room.create",{},{roomId:null,expectedVersion:0});assert.equal(wx.sockets[0].sent.at(-1).roomId,null);assert.equal(wx.sockets[0].sent.at(-1).expectedVersion,0);});

test("realtime client ignores snapshots older than its current room version",()=>{const{RealtimeClient}=load();const wx=fakeWx();const client=new RealtimeClient({wxApi:wx,baseUrl:"ws://localhost:8080",userId:"u-version"});client.connect();wx.sockets[0].handlers.open();wx.sockets[0].handlers.message({data:JSON.stringify({type:"room.snapshot",payload:{roomId:"r1",version:9,phase:"PLAYING"}})});wx.sockets[0].handlers.message({data:JSON.stringify({type:"room.snapshot",payload:{roomId:"r1",version:8,phase:"WAITING"}})});assert.equal(client.publicSnapshot.version,9);assert.equal(client.publicSnapshot.phase,"PLAYING");});
